image: ubuntu

test_script:
#- ps: dir1
- ps: $progressPreference = 'SilentlyContinue'
- ps: bash -c ls; $?; $LASTEXITCODE; $Error
- ps: bash -c 'ls aaa'; $?; $LASTEXITCODE; $Error
- ps: Install-Module -Name Pester -Repository PSGallery -Scope CurrentUser; $?; $LASTEXITCODE; $Error

build: off
