image: ubuntu

test_script:
#- ps: ./tests/debug.ps1
#- ps: dir1
- bash -c 'ls -al'
- ps: bash -c 'ls -al'
#- ps: bash -c 'ls aaa'
- ps: Write-Host 'Hello!'
- ps: Install-Module -Name Pester -Repository PSGallery -Scope CurrentUser -Force

build: off
