image: ubuntu

test_script:
- ps: ./tests/debug.ps1; $?
#- ps: dir1
- ps: bash -c ls
#- ps: bash -c 'ls aaa'
- ps: Install-Module -Name Pester -Repository PSGallery -Scope CurrentUser -Force; $?

build: off
