image: ubuntu

test_script:
- ps: |
    ./tests/debug.ps1; $?;
		$exitCode = 0
		$errorResult = 'False'

		if ($LASTEXITCODE -ne $null -and $LASTEXITCODE -ne 0) {
			$exitCode = $LASTEXITCODE
		} elseif (-not $?) {
			$errorResult = 'True'
		}
    $exitCode
    $errorResult

#- ps: dir1
- ps: bash -c ls
#- ps: bash -c 'ls aaa'
- ps: Install-Module -Name Pester -Repository PSGallery -Scope CurrentUser -Force

build: off
